create table public.tweb_mutasi_pengajuan (
  id character varying(36) not null,
  nik character varying(16) null,
  nama character varying(255) null,
  tempat_lahir character varying(100) null,
  tanggal_lahir date null,
  jenis_kelamin character varying(20) null,
  agama character varying(50) null,
  clusterdesa_id character varying(36) null,
  jenis_mutasi character varying(50) not null,
  keterangan text null,
  tipe_proses character varying(20) not null default 'OFFLINE'::character varying,
  req_method character varying(20) not null default 'OFFLINE'::character varying,
  status character varying(50) not null default 'PENDING'::character varying,
  feedback_sekdes text null,
  tahun_periode character varying(4) not null default '2026'::character varying,
  created_by character varying(36) null,
  approved_by character varying(36) null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp with time zone null default CURRENT_TIMESTAMP,
  parent character varying null,
  keluarga_id character varying(36) null,
  constraint tweb_mutasi_pengajuan_pkey primary key (id),
  constraint tweb_mutasi_pengajuan_clusterdesa_id_fkey foreign KEY (clusterdesa_id) references tweb_clusterdesa (id),
  constraint tweb_mutasi_pengajuan_keluarga_id_fkey foreign KEY (keluarga_id) references tweb_keluarga (id),
  constraint tweb_mutasi_pengajuan_parent_fkey foreign KEY (parent) references tweb_mutasi_pengajuan (id)
) TABLESPACE pg_default;