create table public.tweb_survei_kelayakan (
  id character varying(36) not null,
  penduduk_id character varying(36) not null,
  nik character varying(16) not null,
  nama character varying(255) not null,
  skor integer not null default 0,
  kategori character varying(100) not null,
  indikator_detail text not null,
  jenis_dinding character varying(100) null,
  jenis_lantai character varying(100) null,
  sanitasi character varying(100) null,
  penghasilan_bulanan numeric(12, 2) null,
  ada_lansia boolean null default false,
  tipe_proses character varying(20) not null default 'OFFLINE'::character varying,
  status character varying(50) not null default 'PENDING'::character varying,
  feedback_sekdes text null,
  tahun_periode character varying(4) not null default '2026'::character varying,
  created_by character varying(36) not null,
  approved_by character varying(36) null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp with time zone null default CURRENT_TIMESTAMP,
  sumber_air text null,
  constraint tweb_survei_kelayakan_pkey primary key (id),
  constraint tweb_survei_kelayakan_penduduk_id_fkey foreign KEY (penduduk_id) references tweb_penduduk (id) on delete CASCADE
) TABLESPACE pg_default;